### ISSUE TITLE
Cannot delete individual health monitor chat messages

### ISSUE THREAD

**Issue by notrealdan** [rockshow888/health-monitor#2]
Is there a way to delete an individual health monitor message from the chat, like normal chat messages?  Right now, the only way I can see to remove these messages is to clear the entire chat.  It would be useful to be able to delete them selectively (by the GM only) when desired.

**Comment by rockshow888** [comment]
There is no way to delete a single message. This was a choice because showing the delete button (as normal for chat message) would have an negative impact on the module chat formatting. Maybe in a future I would implement an hover delete option. If this is important to you contat me on discord and i'll show you how to modify the code tho show the delete button.
